version: ${APP_VERSION}

services:
  mysql:
    container_name: sql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  web:
    container_name: web
    build:
      context:
        ./docker/php
      args:
        INDEX_PATH: ${INDEX_PATH}
        IMAGE_PHP_VERSION: ${IMAGE_PHP_VERSION}
        IMAGE_NODE_VERSION: ${IMAGE_NODE_VERSION}
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html/

volumes:
  mysql: