version: '1.0.0'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: symfony_database
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  web:
    image: php:8.1-apache
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html/

volumes:
  mysql: