version: ${APP_VERSION}

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    build: ./docker/php/
    restart: always
    ports:
      - '8077:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  web:
    image: php:8.1-apache
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html/

volumes:
  mysql: